apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: vault-up
  namespace: aura
  labels:
    team: aura
spec:
  image: ghcr.io/nais/vault-up:latest
  port: 8080
  liveness:
    path: /metrics
  readiness:
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "20m"
      memory: "64Mi"
  vault:
    enabled: true

