name: Build and deploy image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
jobs:
  build_and_push:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: aura # required
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required
