on:
  workflow_dispatch:
  push:
    branches:
      - deploy

env:
  TOKEN_URL: https://4642-85-165-193-29.eu.ngrok.io

jobs:
  test-token:
    # Enable token usage
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Getting token from Github"
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "Signing in using token"
          curl -H "Authorization:Bearer $TOKEN" "$TOKEN_URL/github/deploy/up" -X POST -d '{"imageTag":"new"}'
          echo "Done"
